---

- name: Install Mailcow Mail Server
  hosts: localhost
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: System update
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Dist upgrade
      apt:
        upgrade: dist
      register: upgrade_output
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - curl
          - git
        state: present
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Add Docker APT key to trusted.gpg.d
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg"
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Download and Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: '0755'
      when: ansible_distribution in ['Ubuntu', 'Debian']


    - name: Replace the /etc/hostname Configuration File
      become: yes
      copy:
        content: 'mail.projeto.com'
        dest: /etc/hostname
      diff: yes
      ignore_errors: yes

    - name: Replace the /etc/hosts Configuration File
      become: yes
      copy:
        content: 'your_ip_address mail.projeto.com mail' # Change your_ip_address to yout IP Address
        dest: /etc/hosts
      diff: yes
      ignore_errors: yes

    - name: Clone Mailcow-Dockerized Repository
      git:
        repo: https://github.com/mailcow/mailcow-dockerized.git
        dest: /home/nuno/Documents/mailcow-dockerized
      become: yes

    - name: Navigate to Mailcow-Dockerized Directory
      shell: cd /home/nuno/Documents/mailcow-dockerized
      become: yes

    - name: Generate mailcow.conf File
      shell: ./generate_config.sh
      environment:
        MAILCOW_HOSTNAME: "mail.projeto.com"
        MAILCOW_TZ: "Europe/Lisbon"
        MAILCOW_BRANCH: "1"
      args:
        executable: /bin/bash
        chdir: /home/nuno/Documents/mailcow-dockerized
        creates: mailcow.conf
      tags:
        - skip_ansible_lint

    - name: Run docker-compose up -d
      command: docker-compose up -d
      args:
        chdir: /home/nuno/Documents/mailcow-dockerized
      become: yes
