---

- name: Update
  hosts: localhost
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0

  tasks:
    - name: System Update
      apt:
        update_cache: yes
      changed_when: false

    - name: Dist Upgrade
      apt:
        upgrade: dist
      register: upgrade_output

    - name: Install Unattended Upgrades
      package:
        name: unattended-upgrades
        state: latest

    - name: Get List of Upgradable Packages
      shell: apt list --upgradable | awk -F '/' 'NR>1 {print $1}'
      register: upgradable_packages
      changed_when: false

    - name: Update All Packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ upgradable_packages.stdout_lines }}"

    - name: Get List of Packages to Purge
      shell: dpkg --list | grep ^rc | awk '{print $2}'
      register: packages_to_purge
      changed_when: false

    - name: Purge Unused Packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_purge.stdout_lines }}"

    - name: Run apt Autoremove
      shell: apt autoremove --assume-yes
